### PR TITLE
Update golang to v1.15, remove dependency on terraform-plugin-sdk

### PR DESCRIPTION
**Pull request by robgmills**
### Why?

`github.com/hashicorp/terraform-plugin-sdk/v2` made the `hashcode` helper implementation module private.  By removing the dependency on the terraform-plugin-sdk, it opens this client library up to use in applications other than as a terraform provider.

This also makes it easier to stay up-to-date with the terraform-plugin-sdk in the provider that's built on top of this library, as the provider dependency is only required at that level.

### What this does

- updates the version of golang to 1.15
- removes the dependency on the terraform-plugin-sdk
- Adds a `.gitignore` file that, admittedly, ignores files specific to my workflow in [setting environment variables with `direnv`](https://direnv.net/)
- Adds a debug log to output non-sensitive request parameters before making the request so that you can compare the request and response.

### Tests
```sh
λ › git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
λ › git rev-parse --short HEAD
ecde77c
λ › make test
go vet ./...
go fmt ./...
go test -v ./...
=== RUN   TestClient__fail
--- PASS: TestClient__fail (0.00s)
=== RUN   TestClient_NewRequest
DEBUG: "baz=bar&foo=bar"
--- PASS: TestClient_NewRequest (0.00s)
=== RUN   TestDomain__GetDomains
[....]
ok      github.com/adamdecaf/namecheap
```

### Thanks!

Thanks for sharing this work!  It's helped me get moving on a personal project faster than if I had done it from scratch!  I'm a total Go-noob and I appreciate any constructive feedback!

### CODE REVIEW

**Comment by adamdecaf** [comment]
Thanks a ton!

**Comment by adamdecaf** [comment]
Would releasing v1.2.0 help get the terraform provider upgraded?

**Comment by robgmills** [comment]
Thanks for accepting my PR!  If you cut a new release of this client, I could use it to update the terraform provider to use the v2 terraform-plugin-sdk.  I'm looking at doing that now.  I'm still trying to get the terraform provider acceptance tests to pass before making any changes so I suspect you've got some time before waiting on a new release might be blocking that update.

**Comment by adamdecaf** [comment]
Sounds good! I released v1.2.0 -- https://github.com/adamdecaf/namecheap/releases/tag/v1.2.0

**Comment by robgmills** [comment]
Thanks!

**Pull request merged**
